fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    inifile: git://github.com/puppetlabs/puppetlabs-inifile.git


  forge_modules:
    firewall: "puppetlabs/firewall"
    stdlib: "puppetlabs/stdlib"
    limits: "puppetlabs/limits"
    wget: "maestrodev/wget"
    augeasproviders_sysctl: "herculesteam/augeasproviders_sysctl"
    tomcat:
       repo: "puppetlabs/tomcat"
       ref: "1.4.1"
    consul:
       repo: "KyleAnderson/consul"
       ref: "3.2.0"
    archive:
       repo: "puppet/archive"
       ref: "1.3.0"

  symlinks:
    rk_tomcat: "#{source_dir}"
